spring.application.name=emi-planner

spring.datasource.url=jdbc:mysql://db:3306/emi_planner
#use env variables during production
spring.datasource.username=emi_user
spring.datasource.password=emi_password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#use env variables during production
jwt.secret=your-super-secure-secret-key-that-is-at-least-32-characters
jwt.expiration=86400000
